# Generated by Django 5.2.4 on 2025-07-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="registration",
            name="guardian_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="registration",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
