# Generated by Django 5.2.4 on 2025-08-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("guardian_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("father_name", models.CharField(max_length=100)),
                ("mother_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=255)),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("B.Tech", "B.Tech"),
                            ("M.Tech", "M.Tech"),
                            ("Diploma", "Diploma"),
                            ("BCA", "BCA"),
                            ("MCA", "MCA"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("Computer Science", "Computer Science"),
                            ("Electrical", "Electrical"),
                            ("Mechanical", "Mechanical"),
                            ("Civil", "Civil"),
                            ("Information Technology", "Information Technology"),
                            ("Electronics", "Electronics"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("1 Year", "1 Year"),
                            ("2 Year", "2 Year"),
                            ("3 Year", "3 Year"),
                            ("4 Year", "4 Year"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("1st", "1st"),
                            ("2nd", "2nd"),
                            ("3rd", "3rd"),
                            ("4th", "4th"),
                            ("5th", "5th"),
                            ("6th", "6th"),
                            ("7th", "7th"),
                            ("8th", "8th"),
                        ],
                        max_length=10,
                    ),
                ),
                ("college_name", models.CharField(max_length=200)),
                (
                    "percentage_or_cgpa",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "course_name",
                    models.CharField(
                        choices=[
                            ("Web Development", "Web Development"),
                            ("Data Science", "Data Science"),
                            ("Python Programming", "Python Programming"),
                            ("JavaScript", "JavaScript"),
                            ("React Native", "React Native"),
                            ("UI/UX Design", "UI/UX Design"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("1 Month", "1 Month"),
                            ("2 Months", "2 Months"),
                            ("3 Months", "3 Months"),
                            ("45 Days", "45 Days"),
                            ("6 Months", "6 Months"),
                            ("JOT", "JOT"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("Online", "Online"),
                            ("Offline", "Offline"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
